### ISSUE TITLE
Midi Devices Windows 10

### ISSUE THREAD

**Issue by mburn0403** [mabe-at/byomb#10]
Midi Devices sind nach der Installation unter Windows 10 X64 im Webinterface nicht sichtbar

**Comment by mburn0403** [comment]
habe folgendes herausgefunden:

nach folgen der Anleitung auf http://trac.chrisarndt.de/code/wiki/python-rtmidi/install-windows

findet die dort beschriebene Prüfung: 

> cd ..
> python
> 
> > > import rtmidi
> > > rtmidi.API_WINDOWS_MM in rtmidi.get_compiled_api()
> > > True
> > > midiout = rtmidi.MidiOut()
> > > midiout.get_ports()

alle vorhandenen Midi Devices - vielleicht hilft das?

LG

**Comment by mburn0403** [comment]
Noch ein Ansatz: https://github.com/elieserdejesus/JamTaba/issues/98

**Comment by mabe-at** [comment]
Okay. Ich hab's jetzt nachgestellt und zum Laufen bekommen.

Prinzipiell Python 2.7 32bit verwenden.

Visual Studio 2008 Express downloaden und Visual C++ 2008 installieren.
https://go.microsoft.com/fwlink/?LinkId=104679

python-rtmidi downloaden (https://github.com/SpotlightKid/python-rtmidi) und entpacken.

Unter https://github.com/SpotlightKid/python-rtmidi/blob/master/INSTALL-windows.rst gibt es ein paar Hinweise.

Im File setup.py gibt es die Zeile
`WINLIB_DIR = r'C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib'`

Überprüfen ob es das Verzeichnis C:\Program Files\Microsoft SDKs\Windows\v6.0A\Lib gibt.

Wenn nicht dann nach dem File `WinMM.lib` suchen.
Das entsprechende Verzeichnis in `setup.py` anpassen und in der Kommandozeile `python setup.py install` ausführen.

Dann sollte rtmidi und mido funktionieren.

**Comment by mabe-at** [comment]
closing issue
